### ISSUE TITLE
Provide uninstall script

### ISSUE THREAD

**Issue by nau53** [ioBroker/ioBroker#267] opened 2020-05-01 17:03 UTC
Hello

I've had tried ioBroker at my Linux Mint 19.3. After that I deleted ioBroker with that commands:
`update-rc.d iobroker.sh remove
rm /etc/init.d/iobroker.sh
rm /opt/iobroker/* -R
rmdir /opt/iobroker/
apt-get --purge remove node
apt-get --purge remove nodejs
apt-get autoremove
reboot`

Also I removed node.js and npm and every folder I could find with node.js, ioBroker. I have strange behaviour now while running commands with root. For instance when I do "sudo su"  this appears:
[sudo] password for nau:          
bash: /root/.iobroker/npm_command_fix: No such file or directory

Also with installed node.js or not installed if I try to use npm I got this:
root@automata:/# npm
sudo: unknown user: iobroker
sudo: unable to initialize policy plugin

if I put back ioborker user I can use npm again.

I think ioBroker needs to make uninstalling script for such cases. How can I fix that?

**Comment by AlCalzone** [comment] 2020-05-02 08:31
You can edit your .bashrc and remove these two lines:
```
		# Forces npm to run as $IOB_USER when inside the iobroker installation dir
		source ~/.iobroker/npm_command_fix
```

**Comment by nau53** [comment] 2020-05-02 08:45
> You can edit your .bashrc and remove these two lines:
> 
> ```
> 		# Forces npm to run as $IOB_USER when inside the iobroker installation dir
> 		source /root/.iobroker/npm_command_fix
> ```

Dear AlCalzone
Thank you! It solved all my problems!

**Comment by thost96** [comment] 2020-06-22 12:08
duplicate of #133

**Comment by AlCalzone** [comment] 2020-06-22 19:01
closing as duplicate of #133

**Closed by AlCalzone** 2020-06-22 19:01 UTC
Labels: Installer, Linux, bug, macOS
